apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: webapp
spec:
  selector:
    matchLabels:
      app: webapp
  replicas: 3
  template: #template for the pods
    metadata:
      labels:
        app: webapp
    spec:  
      containers:
      - name: webapp
        image: flachens/node-app
