apiVersion: v1
kind: Pod
metadata:
  name: firstpod
  labels:
    app: firstpod
spec:
  containers:
  - name: nodeapp
    image: flachens/node-app
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"