apiVersion: v1
kind: Service
metadata:
  name: app-service
spec:
  selector:
    app: firstpod
  ports:
    - name: http
      port: 80
      targetPort: 4000
      nodePort: 30001
  type: NodePort
    
