apiVersion: v1
kind: Service
metadata:
  name: net-example
spec:
  selector:
      app: webapp
      release: v2
  ports:
    - name: http
      port: 80
      targetPort: 4000
      nodePort: 30082
  type: NodePort
