apiVersion: v1
kind: Service
metadata:
  name: firstpod-webapp
spec:
  selector:
      app: firstpod
      release: v2
  ports:
    - name: http
      port: 80
      targetPort: 4000
      nodePort: 30082
  type: NodePort